---
- hosts: deploy
  become: True
  tasks:
    - name: Install python pip
      yum: 
        name: python-pip
        state: present
    - name: Install Docker
      yum:
        name: docker
        state: present
    - name: start Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: AWS CLI
      yum:
        name: awscli
        state: present
    - name: Establish a login to ECR
      shell: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 107414687854.dkr.ecr.ap-south-1.amazonaws.com
    - name: Pull the image from ECR to CD server
    #  shell: docker pull 016003963452.dkr.ecr.us-east-1.amazonaws.com/dockerdemopipeline:3
      shell: docker pull 107414687854.dkr.ecr.ap-south-1.amazonaws.com/demoimagerepo:23
    - name: Run the container using the docker image
    #  shell: docker run --name=my-java-app-conatiner -p 8080:8080 --detach 016003963452.dkr.ecr.us-east-1.amazonaws.com/dockerdemopipeline:3
      shell: docker run --name=java-app -p 8080:8080 --detach 107414687854.dkr.ecr.ap-south-1.amazonaws.com/demoimagerepo:23
        
        
